---
- name: Importing exploits list
  include_vars: ../exploits/list.yml

- name: Making exploits folder
  become: yes
  file: path=/exploits/ state=directory owner=vagrant mode=0755

- name: Copying exploits to VPES
  copy: src=../exploits/{{ item }} dest=/exploits/{{ item }} owner=vagrant mode=0777
  with_items: "{{ exploits }}"

- name: Copying attach gdb script
  copy: src=../attachgdb.sh dest=/home/vagrant/attachgdb.sh owner=vagrant mode=0777
  
- name: Configuring xinetd
  become: yes
  template: src=xinetd.j2 dest=/etc/xinetd.d/{{ item }}
  with_items: "{{ exploits }}"

- name: Configuring services
  become: yes
  lineinfile: dest=/etc/services line="{{ item.1 }}		{{ 9000 + item.0 }}/tcp"
  with_indexed_items: "{{ exploits }}"

- name: Restarting xinetd
  become: yes
  service: name=xinetd state=restarted

- name: Returning exploit information
  debug: msg="{{ item.1 }} is running on port {{ 9000 + item.0}}"
  with_indexed_items: "{{ exploits }}"